media: 
  input: static/images
  output: /images
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ date, draft, title ]
    fields:
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ date, draft, title ]
    fields:
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: title
        label: Title
        type: string
      - name: body
        label: Body-HTML
        type: text
  - name: config
    label: Hugo config
    path: hugo.yaml
    type: file
    fields:
      - name: baseURL
        label: baseURL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: languageCode
        label: Language Code
        type: string
      - name: title
        label: Website Title
        type: string
      - name: theme
        label: Website Theme
        type: string